projectorganizer: Add popup panel for navigation
geany/geany-plugins pull request #1341
Opened 2024-04-26 20:20 UTC by techee

This feature allows quick navigation do document/workspace symbols based on their names, open files, and line numbers.

The panel's code is mostly stolen from the LSP plugin which in turn stole it from the Colomban Wendling's Commander plugin.

2024-04-27 13:28 UTC, b4n requested changes
LGTM, see inline comments.

Apart from that, I was kind of disappointed that the "goto file" only lists Geany open documents rather than the project's documents -- maybe you'd like to add that?
Also, I hoped to be able to go to a specific file's line, not only in the current file -- but that's probably less useful in practice.

2024-04-28 12:34 UTC, techee commented
@b4n Thanks for having a look at it - I'll address the changes you suggested.

> Apart from that, I was kind of disappointed that the "goto file" only lists Geany open documents rather than the project's documents -- maybe you'd like to add that?

Definitely makes sense for projectorganizer which knows what files belong to the project. So yes, I should add that. This isn't possible in the LSP plugin from which this feature was taken because the plugin itself doesn't know what files belong to the project (this is only known to the server).

Maybe I could also re-introduce the fuzzy search you use in the Commander plugin so one doesn't have to type the searched query exactly. In the LSP plugin it didn't make sense for the workspace symbols where the server did something like that already but e.g. for file names or file's symbols it could be useful (still we probably shouldn't use it for workspace symbols because there's way too many of them and filtering them could take too long because of this).

> Also, I hoped to be able to go to a specific file's line, not only in the current file -- but that's probably less useful in practice.

Probably not hard to add something like `filename.c:123`, I'm just sure I'd be too lazy to type something like that :-). But maybe e.g. the right arrow could complete the value in the search entry to the selected value in the list so one could then just type `:123`.

2024-05-07 16:22 UTC, techee commented on projectorganizer/src/prjorg-goto-anywhere.c
> +				sym->name = g_strdup(_("line typed above"));
Done (also in the LSP plugin).

2024-05-07 16:23 UTC, techee commented on projectorganizer/src/prjorg-goto-anywhere.c
> +	gint pos = sci_get_current_position(doc->editor->sci);
Fixed, together with some other issues (also in the LSP plugin).

2024-05-07 16:26 UTC, techee commented on projectorganizer/src/prjorg-goto-panel.c
> +	if (icon < _N_ICONS)
I'd prefer if https://github.com/geany/geany/pull/3849/commits/1931fcc2f4d5de46871c85a782903d8c4d41e699 from https://github.com/geany/geany/pull/3849 could be merged and used here. While the icons can be accessed this way, if someone reorganizes something in Geany, it will break. So better have some proper API for accessing these icons.

2024-05-07 16:27 UTC, techee commented on projectorganizer/src/prjorg-goto-panel.c
> +		  return TRUE;
Done.

2024-05-07 16:27 UTC, techee commented on projectorganizer/src/prjorg-goto-panel.c
> +			gchar *normalized_val = g_utf8_normalize(*val, -1, G_NORMALIZE_ALL);
Done.

2024-05-07 16:30 UTC, techee commented
> Apart from that, I was kind of disappointed that the "goto file" only lists Geany open documents rather than the project's documents -- maybe you'd like to add that?

Done in the last commit - open files are sorted before project files and also non-open project files don't have any icon in front of them to distinguish them from the open files.

> Also, I hoped to be able to go to a specific file's line, not only in the current file -- but that's probably less useful in practice.

Not done now, possibly in the future.

2024-06-30 19:47 UTC, techee commented
I've updated this PR to use https://github.com/geany/geany/pull/3916. What's still missing is updating the required Geany API once we bump it in Geany.

2024-08-05 20:55 UTC, techee commented
> What's still missing is updating the required Geany API once we bump it in Geany.

Done now. This PR is complete from my point of view.

Unless there are any objections, I'll squash all the commits into one and merge this PR in about a week.

2024-08-11 17:38 UTC, merged