commander: small improvement on listing and panel width
geany/geany-plugins pull request #1394
Opened 2024-12-14 09:06 UTC by icy

## Motivation

When working  with different directories that have some common files that have long full path name, it's hard to find the right file from the list. This is because the panel's width is 500 and the full path may not be shown completely within the panel as below

```
<-------- visible to  user --------> <----- invisible to users ------------------->

/-----------------------------------\
| /foo/bar/directory/with/very/long-|/path1/name/sample.txt
| Files -> Recent Files -> /foo/bar/|directory/with/very/long-/path1/name/sample.txt
| /foo/bar/directory/with/very/long-|/path2/name/sample.txt
| Files -> Recent Files -> /foo/bar/|directory/with/very/long-/path2/name/sample.txt
\-----------------------------------/

```

In this illustration, when  looking up  `sample.txt`, the user has no idea about the directory  information (both `path1` and `path2` do matching)

## The patches

- [ ] The panel's width is  one half of the width of the Geany window when this amount is greater than or equals to 250
- [ ] Otherwise the panel's width defaults to the width of the Geany window
- [ ] For labels, don't display  full names; only display the parent directory's basename and the file name

The previous illustration now becomes

```
/-----------------------------------\
| name1/sample.txt                  |
| Files -> Recent Files -> /foo/bar/|directory/with/very/long-/path/name1/sample.txt
| name2/sample.txt                  |
| Files -> Recent Files -> /foo/bar/|directory/with/very/long-/path/name2/sample.txt
\-----------------------------------/
```

and this helps user to quickly find the right files. 

Of course this doesn't solve all edge cases when there are a few more levels of  duplication in full path names.

2025-01-04 14:44 UTC, eht16 commented
Could you try to remove the unnecessary white space changes? This would make the diff easier to read and less noisy (I'm aware I can disable showing whitespace changes but they are still there).

Or we manage to convince @b4n to accept stripping trailing whitespace :).

2025-01-04 16:36 UTC, icy commented
Hi @eht16 ,

Thanks for your suggestion. I will update the patch with spaces removed.

2025-01-05 11:38 UTC, icy commented
> Hi @eht16 ,
> 
> Thanks for your suggestion. I will update the patch with spaces removed.

I am using Geany to edit the file, and one of the plugin/functions of the editor has edited the spaces without my intention. I have tried to squash the commits and give another try today.

2025-01-05 14:28 UTC, icy commented
> Could you try to remove the unnecessary white space changes? This would make the diff easier to read and less noisy (I'm aware I can disable showing whitespace changes but they are still there).
> 
> Or we manage to convince @b4n to accept stripping trailing whitespace :).

Hi @eht16,

I've updated my pull request and I think it's easier to review now.  Please have a look when you've time. 

Thank you very much.

2025-02-04 23:26 UTC, b4n requested changes
I'm not against a way to better discriminate between similar-looking paths, but I think it needs more work not to be as specific to your use case where the parent's directory name is enough.

Also, please split changes into individual commits (e.g. the change to window size seem unrelated), and make sure the rationale behind each change is clear -- for example, the one behind the window size isn't clear to me.

2025-02-04 23:26 UTC, b4n commented on commander/src/commander-plugin.c
> +        }
This seems overly fragile to me, as menu item labels can contain pretty much anything, including `/`s.

Take for example *Edit → Insert Date → yyyy/mm/dd*: with this change, it appears as *mm/dd*.

2025-02-04 23:26 UTC, b4n commented on commander/src/commander-plugin.c
> +                                            dirname_basename,
Here it's not as problematic as those *are* paths.  However, the dirname is not necessarily helping much as it might very well still be the same (e.g. if there are `foo/src/main.c` and `bar/src/main.c`, this change won't help).

If this is really an issue you encounter, I suggest investigating a more clever solution, possibly verifying there are effectively duplicates, and then compute the difference between the paths in order to show parts that are actually relevant.  IIRC there's something like that in Geany's *got to* popup you might get inspiration from.

Once that's dealt with I wonder what the best visual layout would be… maybe `<big>$basename</big> <small>($path_diff)</small>\n<small><i>$path</i></small>`?  Not tested though, but I think preserving focus on the filename, or actually what's really relevant in it, is important.  So maybe even highlight the different parts?

2025-02-04 23:26 UTC, b4n commented on commander/src/commander-plugin.c
> +  }
Is 500 really too big?  Otherwise if the goal is to make it *bigger*, then the threshold should be whatever makes it larger than 500 (math suggests it'd be 1000).

Also note that this is *not* dynamic during a Geany session, it's only the default size when opening the panel for the first time, if you change the Geany window size later it won't affect this.  This is not necessarily an issue though.

2025-02-04 23:26 UTC, b4n commented on commander/src/commander-plugin.c
> +}
Please bring the trailing newline back :slightly_smiling_face:

2025-02-05 18:30 UTC, icy commented on commander/src/commander-plugin.c
> +  }
> Is 500 really too big? Otherwise if the goal is to make it bigger, then the threshold should be whatever makes it larger than 500 (math suggests it'd be 1000).

When the main window has some moderate size , I want(ed) the commander's panel has  relatively smaller size. When the main window  is  too small (< 500), I want to see the  commander of the same size (otherwise it's too small  to show any thing if I  get it right.)

I  admit my calculation is  bad. It's  better that I used some min() function instead.

> Also note that this is not dynamic during a Geany session, it's only the default size when opening the panel for the first time, if you change the Geany window size later it won't affect this. This is not necessarily an issue though

I've also noticed that, thanks for your confirmation.

2025-02-05 18:35 UTC, icy commented on commander/src/commander-plugin.c
> +        }
Yes, that may be a problem, and in that case, it's also possible to see all details in the smaller part of the menu item ( `Edit → Insert Date → yyyy/mm/dd`).

2025-02-05 18:48 UTC, icy commented on commander/src/commander-plugin.c
> +                                            dirname_basename,
I agree that your suggestion  would be better and would address all cases well. 

I was actually thinking if I could do some computing for all items before getting the best display option. However, I  think that would require more resources, and I don't think it's not worth trading. I was really getting some hard time using our plugin, and the best idea I've been able to share, is this (wip) pull request.

I will spend a little more time on this, at least for my own usage. If you think there should be more efficient way to address the problem, I can help to open an issue and hopefully someone from the community can help.

Thank you a lot for your time.

2025-07-23 06:34 UTC, icy commented
I'd  close this patch, as I  am unable to invest time  on this. I hope the problem  may get some attention  and someone would find  better way to address it. Sorry for any noise.

2025-07-23 06:34 UTC, closed without merging